# Generated by Django 4.1.4 on 2022-12-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(default='John Doe', max_length=100)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
